### ISSUE TITLE
Errors when compiling the executable with on Chromebook

### ISSUE THREAD

**Issue by TG20YT** [cuckydev/SoniCPort#7]
I was trying to compile the executable (I had generated the build files already) and got these messages, causing it to abort (I use the Chromebook Crostini Linux and had all the dependencies installed)

![image](https://user-images.githubusercontent.com/79722408/164048249-147e754d-2b54-456d-8444-b308ef5aa03d.png)

_**tg20@penguin:~/SoniCPort$ cmake --build build --config Release
[  3%] Built target bin2h
[  3%] Building C object CMakeFiles/SoniCPort.dir/src/Object/HUD.c.o
/home/tg20/SoniCPort/src/Object/HUD.c: In function ‘Obj_HUD’:
/home/tg20/SoniCPort/src/Object/HUD.c:52:5: error: a label can only be part of a statement and a declaration is not a statement
   52 |     uint8_t frame = 0;
      |     ^~~~~~~
gmake[2]: *** [CMakeFiles/SoniCPort.dir/build.make:2000: CMakeFiles/SoniCPort.dir/src/Object/HUD.c.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:124: CMakeFiles/SoniCPort.dir/all] Error 2
gmake: *** [Makefile:103: all] Error 2**_

Is there something I'm missing or is it supposed to do that?

**Comment by cuckydev** [comment]
It looks here like I forgot to put brackets in a switch case, I'll try to make a commit to fix this real quick

**Comment by cuckydev** [comment]
Fixed in https://github.com/cuckydev/SoniCPort/commit/8976e22aa20ace8cb06cef15dba654a393e05053
